### ISSUE TITLE
Loader-specific util class

### ISSUE THREAD

**Issue by Wyvest** [Deftu/MultiCraft#3]
Features
- method to see whether a mod is loaded
- method to see if a mod is being loaded (would be forge specific because fabric doesn't work like that)
- method to get info of the loaded mod (again, would be forge specific)
- method to get a list of loaded mods
- get enum of loaders

**Comment by Deftu** [comment]
Added in cfb2cb69c06958bce0c459dd7e0d407a424b9a51.
